package nl.siegmann.epublib.domain;

import nl.siegmann.epublib.service.MediatypeService;
import nl.siegmann.epublib.util.StringUtil;

import javax.xml.namespace.QName;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * A Book's collection of Metadata.
 * In the future it should contain all Dublin Core attributes, for now it contains a set of often-used ones.
 *
 * @author paul
 *
 */
public class Metadata implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -2437262888962149444L;

    private static final String DEFAULT_LANGUAGE = "en";

    private boolean autoGeneratedId = true;
    private List<Author> authors = new ArrayList<Author>();
    private List<Author> contributors = new ArrayList<Author>();
    private List<Date> dates = new ArrayList<Date>();
    private String language = DEFAULT_LANGUAGE;
    private Map<QName, String> otherProperties = new HashMap<QName, String>();
    private List<String> rights = new ArrayList<String>();
    private List<String> titles = new ArrayList<String>();
    private List<Identifier> identifiers = new ArrayList<Identifier>();
    private List<String> subjects = new ArrayList<String>();
    private String format = MediatypeService.EPUB.getName();
    private List<String> types = new ArrayList<String>();
    private List<String> descriptions = new ArrayList<String>();
    private List<String> publishers = new ArrayList<String>();
    private Map<String, String> metaAttributes = new HashMap<String, String>();

    public Metadata() {
        this.identifiers.add(new Identifier());
        this.autoGeneratedId = true;
    }

    public boolean isAutoGeneratedId() {
        return this.autoGeneratedId;
    }

    /**
     * Metadata properties not hard-coded like the author, title, etc.
     *
     * @return Metadata properties not hard-coded like the author, title, etc.
     */
    public Map<QName, String> getOtherProperties() {
        return this.otherProperties;
    }

    public void setOtherProperties(final Map<QName, String> otherProperties) {
        this.otherProperties = otherProperties;
    }

    public Date addDate(final Date date) {
        this.dates.add(date);
        return date;
    }

    public List<Date> getDates() {
        return this.dates;
    }

    public void setDates(final List<Date> dates) {
        this.dates = dates;
    }

    public Author addAuthor(final Author author) {
        this.authors.add(author);
        return author;
    }

    public List<Author> getAuthors() {
        return this.authors;
    }

    public void setAuthors(final List<Author> authors) {
        this.authors = authors;
    }

    public Author addContributor(final Author contributor) {
        this.contributors.add(contributor);
        return contributor;
    }

    public List<Author> getContributors() {
        return this.contributors;
    }

    public void setContributors(final List<Author> contributors) {
        this.contributors = contributors;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(final String language) {
        this.language = language;
    }

    public List<String> getSubjects() {
        return this.subjects;
    }

    public void setSubjects(final List<String> subjects) {
        this.subjects = subjects;
    }

    public void setRights(final List<String> rights) {
        this.rights = rights;
    }

    public List<String> getRights() {
        return this.rights;
    }


    /**
     * Gets the first non-blank title of the book.
     * Will return "" if no title found.
     *
     * @return the first non-blank title of the book.
     */
    public String getFirstTitle() {
        if ((this.titles == null) || this.titles.isEmpty()) {
            return "";
        }
        for (final String title : this.titles) {
            if (StringUtil.isNotBlank(title)) {
                return title;
            }
        }
        return "";
    }


    public String addTitle(final String title) {
        this.titles.add(title);
        return title;
    }

    public void setTitles(final List<String> titles) {
        this.titles = titles;
    }

    public List<String> getTitles() {
        return this.titles;
    }

    public String addPublisher(final String publisher) {
        this.publishers.add(publisher);
        return publisher;
    }

    public void setPublishers(final List<String> publishers) {
        this.publishers = publishers;
    }

    public List<String> getPublishers() {
        return this.publishers;
    }

    public String addDescription(final String description) {
        this.descriptions.add(description);
        return description;
    }

    public void setDescriptions(final List<String> descriptions) {
        this.descriptions = descriptions;
    }

    public List<String> getDescriptions() {
        return this.descriptions;
    }

    public Identifier addIdentifier(final Identifier identifier) {
        if (this.autoGeneratedId && (!(this.identifiers.isEmpty()))) {
            this.identifiers.set(0, identifier);
        } else {
            this.identifiers.add(identifier);
        }
        this.autoGeneratedId = false;
        return identifier;
    }

    public void setIdentifiers(final List<Identifier> identifiers) {
        this.identifiers = identifiers;
        this.autoGeneratedId = false;
    }

    public List<Identifier> getIdentifiers() {
        return this.identifiers;
    }

    public void setFormat(final String format) {
        this.format = format;
    }

    public String getFormat() {
        return this.format;
    }

    public String addType(final String type) {
        this.types.add(type);
        return type;
    }

    public List<String> getTypes() {
        return this.types;
    }

    public void setTypes(final List<String> types) {
        this.types = types;
    }

    public String getMetaAttribute(final String name) {
        return this.metaAttributes.get(name);
    }

    public void setMetaAttributes(final Map<String, String> metaAttributes) {
        this.metaAttributes = metaAttributes;
    }
}
